<a href="https://colab.research.google.com/github/Mayuri-thatikonda/entrepreneurship/blob/main/entrepreneurship.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('data.csv')


In [3]:
dataset.head()

EducationSector  ...  y
0  Engineering Sciences  ...  1
1  Engineering Sciences  ...  0
2  Engineering Sciences  ...  0
3  Engineering Sciences  ...  0
4  Engineering Sciences  ...  1

[5 rows x 17 columns]

In [4]:
dataset.columns

Index(['EducationSector', 'IndividualProject', 'Age', 'Gender', 'City',
       'Influenced', 'Perseverance', 'DesireToTakeInitiative',
       'Competitiveness', 'SelfReliance', 'StrongNeedToAchieve',
       'SelfConfidence', 'GoodPhysicalHealth', 'MentalDisorder', 'KeyTraits',
       'ReasonsForLack', 'y'],
      dtype='object')

In [5]:
dataset['y'].nunique()

2

In [6]:
dataset.dtypes

EducationSector           object
IndividualProject         object
Age                        int64
Gender                    object
City                      object
Influenced                object
Perseverance               int64
DesireToTakeInitiative     int64
Competitiveness            int64
SelfReliance               int64
StrongNeedToAchieve        int64
SelfConfidence             int64
GoodPhysicalHealth         int64
MentalDisorder            object
KeyTraits                 object
ReasonsForLack            object
y                          int64
dtype: object

In [7]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 219 entries, 0 to 218
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   EducationSector         219 non-null    object
 1   IndividualProject       219 non-null    object
 2   Age                     219 non-null    int64 
 3   Gender                  219 non-null    object
 4   City                    219 non-null    object
 5   Influenced              219 non-null    object
 6   Perseverance            219 non-null    int64 
 7   DesireToTakeInitiative  219 non-null    int64 
 8   Competitiveness         219 non-null    int64 
 9   SelfReliance            219 non-null    int64 
 10  StrongNeedToAchieve     219 non-null    int64 
 11  SelfConfidence          219 non-null    int64 
 12  GoodPhysicalHealth      219 non-null    int64 
 13  MentalDisorder          219 non-null    object
 14  KeyTraits               219 non-null    object
 15  Reason

In [8]:
dataset.nunique()

EducationSector            9
IndividualProject          2
Age                       10
Gender                     2
City                       2
Influenced                 2
Perseverance               5
DesireToTakeInitiative     5
Competitiveness            5
SelfReliance               5
StrongNeedToAchieve        5
SelfConfidence             5
GoodPhysicalHealth         5
MentalDisorder             2
KeyTraits                  5
ReasonsForLack            44
y                          2
dtype: int64

In [9]:
dataset.drop(['ReasonsForLack','EducationSector'],axis=1,inplace=True)

In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dataset = dataset[['City', 'IndividualProject', 'Gender', 'Influenced',
       'MentalDisorder', 'KeyTraits',]].apply(le.fit_transform)
print(dataset)

     City  IndividualProject  Gender  Influenced  MentalDisorder  KeyTraits
0       1                  0       1           0               1          0
1       0                  1       1           1               1          3
2       1                  0       1           0               0          0
3       1                  1       1           1               0          2
4       1                  1       1           1               1          3
..    ...                ...     ...         ...             ...        ...
214     1                  1       1           1               1          1
215     1                  1       1           0               0          4
216     1                  1       0           1               0          3
217     1                  0       1           0               0          0
218     0                  1       1           1               0          0

[219 rows x 6 columns]


In [11]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [12]:
print(y)

[0 3 0 2 3 1 4 4 0 4 2 0 4 3 0 1 3 1 0 0 3 1 3 3 4 3 0 4 4 0 4 4 3 2 1 0 4
 0 1 1 1 1 3 1 0 1 4 1 1 0 3 1 4 4 0 1 1 4 0 4 1 1 1 0 1 0 4 1 4 2 2 1 3 2
 1 0 3 3 2 1 1 3 2 1 3 1 0 1 3 0 1 3 1 1 1 0 0 0 0 3 0 3 0 3 4 0 4 0 4 0 3
 1 1 1 1 4 1 1 4 1 1 3 0 1 3 4 1 1 1 1 1 0 0 0 4 0 1 3 0 2 4 0 1 3 1 0 0 0
 1 1 1 0 1 1 4 1 1 1 3 2 0 0 3 0 0 3 3 1 1 4 0 0 0 0 4 0 4 0 1 4 0 0 4 4 0
 3 1 0 4 0 0 1 0 1 4 1 4 1 0 1 4 1 3 1 0 1 1 1 3 1 0 3 4 4 1 4 3 0 0]


In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [14]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [15]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [16]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 1]
 [0 1]
 [1 1]
 [0 0]
 [3 3]
 [1 3]
 [1 0]
 [0 1]
 [0 0]
 [1 0]
 [0 1]
 [1 1]
 [4 1]
 [0 1]
 [1 3]
 [4 1]
 [0 1]
 [0 0]
 [1 4]
 [0 0]
 [0 1]
 [4 4]
 [1 1]
 [0 1]
 [0 0]
 [0 1]
 [0 3]
 [1 1]
 [1 0]
 [1 0]
 [1 4]
 [1 1]
 [0 2]
 [0 4]
 [4 3]
 [0 2]
 [1 1]
 [4 1]
 [1 1]
 [0 1]
 [1 4]
 [0 2]
 [1 0]
 [1 3]]


In [17]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 5  5  0  0  0]
 [10  7  0  0  3]
 [ 3  0  0  0  0]
 [ 1  3  0  1  1]
 [ 1  3  0  0  1]]


0.3181818181818182